import { 
  AiOutlinePercentage,
  AiOutlineBook,
  AiOutlineEdit,
  AiOutlineCopy,
  AiOutlineTool,
  AiOutlineReload,
  AiOutlineRobot,
  AiOutlineBarcode,
  AiOutlineMessage,
  AiOutlineFileText,
  AiOutlineCheckSquare,
  AiOutlineClockCircle,
  AiOutlineThunderbolt,
  AiOutlinePlayCircle,
  AiOutlinePlusCircle,
  AiOutlineGlobal,
  AiOutlineHeart,
  AiOutlineSend,
  AiOutlineWallet,
  AiOutlineGift,
  AiOutlineBarChart,
  AiOutlineLineChart,
  AiOutlineTeam,
  AiOutlineAppstore,
} from 'react-icons/ai';

export const iconMap = {
  AiOutlinePercentage: AiOutlinePercentage,
  AiOutlineBook: AiOutlineBook,
  AiOutlineEdit: AiOutlineEdit,
  AiOutlineCopy: AiOutlineCopy,
  AiOutlineTool: AiOutlineTool,
  AiOutlineReload: AiOutlineReload,
  AiOutlineRobot: AiOutlineRobot,
  AiOutlineBarcode: AiOutlineBarcode,
  AiOutlineMessage: AiOutlineMessage,
  AiOutlineFileText: AiOutlineFileText,
  AiOutlineCheckSquare: AiOutlineCheckSquare,
  AiOutlineClockCircle: AiOutlineClockCircle,
  AiOutlineThunderbolt: AiOutlineThunderbolt,
  AiOutlinePlayCircle: AiOutlinePlayCircle,
  AiOutlinePlusCircle: AiOutlinePlusCircle,
  AiOutlineGlobal: AiOutlineGlobal,
  AiOutlineHeart: AiOutlineHeart,
  AiOutlineSend: AiOutlineSend,
  AiOutlineWallet: AiOutlineWallet,
  AiOutlineGift: AiOutlineGift,
  AiOutlineBarChart: AiOutlineBarChart,
  AiOutlineLineChart: AiOutlineLineChart,
  AiOutlineTeam: AiOutlineTeam,
  AiOutlineAppstore: AiOutlineAppstore,
};
